"""add property fields

Revision ID: 5c13f5a93b64
Revises: e381fdb6c523
Create Date: 2026-04-03 14:45:55.637900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c13f5a93b64'
down_revision: Union[str, Sequence[str], None] = 'e381fdb6c523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('city', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('listing_type', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('bathrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'bathrooms')
    op.drop_column('properties', 'listing_type')
    op.drop_column('properties', 'city')
    # ### end Alembic commands ###
